export const QUERY_VALIDATION_CONCURRENCY = 64
export const PROJECTED_QUERY_VALIDATION_CONCURRENCY = 64
export const SCAN_VALIDATION_CONCURRENCY = 64
export const PROJECTED_SCAN_VALIDATION_CONCURRENCY = 64
